version: 2.1

parameters:
  node-version:
    type: string
    default: "16.17.0"

jobs:
  build:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - run: yarn install --immutable --immutable-cache
      - run: yarn dedupe --check
      - run: ./.circleci/install-ipfs.sh
      - run: openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out test-deploy-key.pem -outform PEM
      - run: |
          echo '> ipfs key import test-deploy-key --format=pem-pkcs8-cleartext ./test-deploy-key.pem'
          export IPNS_KEY=$(ipfs key import test-deploy-key --format=pem-pkcs8-cleartext ./test-deploy-key.pem)
          echo "export IPNS_KEY=$IPNS_KEY"
          echo "export IPNS_KEY=$IPNS_KEY" >> $BASH_ENV
      - run: ipfs key list -l
      - run: |
          echo '> yarn test-deploy'
          export IPFS_CID=$(yarn test-deploy)
          echo "export IPFS_CID=$IPFS_CID"
          echo "export IPFS_CID=$IPFS_CID" >> $BASH_ENV
      - run: yarn start test-deploy-key $IPFS_CID
      - run: curl -s "http://$IPNS_KEY.ipns.localhost:8080" | grep '<h1>Hello!</h1>'
